/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_PIPELINE_H_
#define INCLUDE_PIPELINE_H_

#include "image.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

int pipeline_serial(image_dir_t* image_dir);
int pipeline_pthread(image_dir_t* image_dir);
int pipeline_tbb(image_dir_t* image_dir);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* INCLUDE_PIPELINE_H_ */
